# Generated by Django 4.1 on 2022-10-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlink',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
