# Generated by Django 4.1 on 2022-10-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_accountlink_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default='kddd1', max_length=50),
            preserve_default=False,
        ),
    ]
