# Generated by Django 4.1 on 2022-10-05 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_activation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlink',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
