# Generated by Django 4.1 on 2022-10-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_accountlink_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='samsuchin', max_length=200),
            preserve_default=False,
        ),
    ]
