# Generated by Django 4.1 on 2022-10-28 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_nickname_user_name_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referrer',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred',
        ),
    ]
