# Generated by Django 4.2.6 on 2023-11-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_user_first_name_remove_user_is_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
