# Generated by Django 4.2.6 on 2023-11-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_user_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('partner', 'Partner'), ('staff', 'Staff'), ('user', 'User')], default='partner', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
