# Generated by Django 4.2.6 on 2023-11-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
