# Generated by Django 4.2.6 on 2023-11-10 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_address_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
