# Generated by Django 4.2.6 on 2023-11-22 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospect', '0003_prospect_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
