# Generated by Django 4.2.6 on 2023-11-23 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospect', '0004_prospect_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='users',
            field=models.ManyToManyField(related_name='prospects', to=settings.AUTH_USER_MODEL),
        ),
    ]
