# Generated by Django 4.2.6 on 2023-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0005_alter_prospect_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
