# Generated by Django 4.2.6 on 2024-01-21 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospect', '0006_prospect_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prospects_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
