# Generated by Django 4.2.6 on 2024-02-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0008_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
