# Generated by Django 4.2.6 on 2024-02-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0010_prospect_client_onboarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='client_scenario',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
