# Generated by Django 4.2.6 on 2024-02-08 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prospect', '0011_prospect_client_scenario_alter_prospect_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
