# Generated by Django 4.2.6 on 2024-02-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0012_prospect_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('self-storage', 'Self Storage'), ('multifamily', 'Multi-Familty')]),
        ),
    ]
