# Generated by Django 4.2.6 on 2024-02-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0013_alter_prospect_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
