# Generated by Django 4.2.6 on 2024-02-18 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0015_dataupload_delete_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataupload',
            name='prospects',
        ),
        migrations.AddField(
            model_name='dataupload',
            name='analyze_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='analyze_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectdata',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataUploads', to='prospect.dataupload'),
        ),
    ]
