# Generated by Django 4.2.6 on 2024-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0016_remove_dataupload_prospects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
