# Generated by Django 4.2.6 on 2024-02-21 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_note_is_smart_alter_note_user'),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendersync',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncs', to='market.lender'),
        ),
        migrations.AlterField(
            model_name='lendersync',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syncs', to='market.note'),
        ),
    ]
