# Generated by Django 4.2.6 on 2023-12-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
