# Generated by Django 4.2.6 on 2024-01-15 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_outreach'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
