# Generated by Django 4.2.6 on 2024-01-15 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0006_prospect_amount'),
        ('market', '0005_outreach_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreach',
            name='title',
        ),
        migrations.AddField(
            model_name='outreach',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreaches', to='prospect.prospect'),
        ),
    ]
