# Generated by Django 4.2.6 on 2024-01-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_outreach_email_content_creation_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outreach',
            old_name='email_content_creation_started',
            new_name='openai_outreach_time',
        ),
        migrations.AddField(
            model_name='outreach',
            name='openai_outreach_run_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='openai_outreach_thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
