# Generated by Django 4.2.6 on 2024-01-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_rename_email_content_creation_started_outreach_openai_outreach_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='openai_outreach_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
