# Generated by Django 4.2.6 on 2024-01-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_outreach_openai_outreach_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='openai_outreach_error',
            field=models.BooleanField(default=False),
        ),
    ]
