# Generated by Django 4.2.6 on 2024-01-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_outreach_openai_outreach_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='email_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
