# Generated by Django 4.2.6 on 2024-02-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_rename_email_sent_at_outreach_email_sent_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='schedule_call_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
