# Generated by Django 4.2.6 on 2024-02-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_outreach_schedule_call_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreach',
            name='openai_outreach_error',
        ),
    ]
