# Generated by Django 4.2.6 on 2024-02-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_documenttype_is_image'),
        ('market', '0015_remove_outreach_openai_outreach_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='email_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.document'),
        ),
    ]
