# Generated by Django 4.2.6 on 2024-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_outreach_email_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='email_subject',
            field=models.CharField(blank=True, null=True),
        ),
    ]
