# Generated by Django 4.2.6 on 2023-11-08 23:47

from django.db import migrations, models
import django.db.models.deletion
import tracker.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('originator', models.CharField(max_length=200)),
                ('borrower', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closing', 'Closing'), ('failed', 'Failed'), ('closed', 'Closed')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('refinance', 'Refinance'), ('construction', 'Construction')], max_length=100)),
                ('property_type', models.CharField(choices=[('hotel', 'Hotel'), ('self-storage', 'Self Storage')])),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to=tracker.utils.get_doc_path)),
                ('type', models.CharField(choices=[('personal-finance', 'Personal Finance Report')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('feedback', models.TextField(blank=True, max_length=1000, null=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.prospect')),
            ],
        ),
    ]
