# Generated by Django 4.2.6 on 2023-11-10 22:04

from django.db import migrations, models
import django.db.models.deletion
import tracker.utils


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0003_prospect_last_updated'),
        ('tracker', '0002_alter_document_prospect_delete_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('revising', 'Revising'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=tracker.utils.get_doc_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='prospect.prospect'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
