# Generated by Django 4.2.6 on 2023-11-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_document_status_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
