# Generated by Django 4.2.6 on 2023-11-13 00:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
