# Generated by Django 4.2.6 on 2023-11-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_document_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='openai_assistant_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='openai_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
