# Generated by Django 4.2.6 on 2023-11-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_document_openai_run_id_document_openai_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='openai_ran_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
