# Generated by Django 4.2.6 on 2023-12-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_document_openai_ran_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client_feedback',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
