# Generated by Django 4.2.6 on 2023-12-12 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0006_prospect_amount'),
        ('tracker', '0010_document_client_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('general_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentTypes', to='prospect.prospect')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracker.documenttype'),
        ),
    ]
