# Generated by Django 4.2.6 on 2023-12-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_documenttype_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='status',
            field=models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('pending', 'Pending'), ('revising', 'Revising'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_uploaded', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('pending', 'Pending'), ('revising', 'Revising'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
    ]
