# Generated by Django 4.2.6 on 2023-12-13 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_documenttype_status_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
