# Generated by Django 4.2.6 on 2023-12-13 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_documenttype_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='prospect',
        ),
    ]
