# Generated by Django 4.2.6 on 2023-12-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_remove_document_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='document_count',
            field=models.IntegerField(default=1),
        ),
    ]
