# Generated by Django 4.2.6 on 2023-12-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_documenttype_document_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='openai_run_file_check_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='openai_thread_file_check_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
