# Generated by Django 4.2.6 on 2024-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_document_overridden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='openai_assistant_id',
            new_name='openai_document_feedback_run_id',
        ),
        migrations.AddField(
            model_name='document',
            name='openai_document_feedback_ran_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='openai_document_feedback_thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
