# Generated by Django 4.2.6 on 2024-01-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_rename_openai_assistant_id_document_openai_document_feedback_run_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='openai_document_feedback_run_id',
            new_name='openai_check_run_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_document_feedback_thread_id',
            new_name='openai_check_thread_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_document_feedback_ran_at',
            new_name='openai_feedback_ran_at',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_run_file_check_id',
            new_name='openai_feedback_run_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_run_id',
            new_name='openai_feedback_thread_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='openai_thread_file_check_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='openai_thread_id',
        ),
    ]
