# Generated by Django 4.2.6 on 2024-01-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_rename_openai_document_feedback_run_id_document_openai_check_run_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='client_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='staff_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='status',
            field=models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('pending', 'Pending'), ('approved', 'Approved')], default='not_uploaded', max_length=100),
        ),
    ]
