# Generated by Django 4.2.6 on 2024-01-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_documenttype_client_notifications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_feedback_ran_at',
            new_name='document_sorted_time',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_ran_at',
            new_name='openai_checked_time',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_check_run_id',
            new_name='openai_document_check_run_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_check_thread_id',
            new_name='openai_document_check_thread_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_feedback_run_id',
            new_name='openai_document_feedback_run_id',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='openai_feedback_thread_id',
            new_name='openai_document_feedback_thread_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_checked',
        ),
        migrations.AddField(
            model_name='document',
            name='openai_document_sort_run_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='openai_document_sort_thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='openai_feedback_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='openai_thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='status',
            field=models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('hidden', 'Hidden')], default='not_uploaded', max_length=100),
        ),
    ]
