# Generated by Django 4.2.6 on 2024-01-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_document_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='smart_checked',
            field=models.BooleanField(default=False),
        ),
    ]
