# Generated by Django 4.2.6 on 2024-01-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_document_smart_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client_comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
