# Generated by Django 4.2.6 on 2024-01-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_rename_client_comments_document_client_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_valid',
        ),
    ]
