# Generated by Django 4.2.6 on 2024-02-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_remove_document_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
